# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "60ad3956ca36744f7db0a22fc338b3b1"
name = "Count On Us"
application_url = "https://shopify.mnbecks.com/app"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [
  "products/update",
  "orders/create",
  "app/uninstalled",
  "orders/updated",
  "refunds/create"
]
  uri = "https://shopify.mnbecks.com/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_locales,read_metaobject_definitions,read_metaobjects,read_orders,read_products,read_shopify_payments_payouts,write_app_proxy,write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [
  "https://shopify.mnbecks.com/auth/callback",
  "https://shopify.mnbecks.com/auth/shopify/callback"
]
