name = "remix"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks"

[commands]
predev = "npm run prisma:generate:best-effort"
dev = "npx prisma migrate deploy && npm exec remix vite:dev -- --host 0.0.0.0 --port 3000"
