# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2dde5654ca0a8aa8ad7423c6e55fcb7f"
name = "Count On Us Dev"
application_url = "https://shopify-dev.mnbecks.com/app"
embedded = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [
  "products/update",
  "orders/create",
  "app/uninstalled",
  "orders/updated",
  "refunds/create"
]
  uri = "https://shopify-dev.mnbecks.com/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,read_locales,read_metaobject_definitions,read_metaobjects,read_orders,read_products,read_shopify_payments_payouts,write_app_proxy,write_files,write_metaobject_definitions,write_metaobjects"

[auth]
redirect_urls = [
  "https://shopify-dev.mnbecks.com/auth/callback",
  "https://shopify-dev.mnbecks.com/auth/shopify/callback"
]

[build]
automatically_update_urls_on_dev = false

[app_proxy]
url = "/api/widget"
subpath = "count-on-us"
prefix = "apps"
